// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/greeter.proto

package greeter

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Gteeter service

func NewGteeterEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Gteeter service

type GteeterService interface {
	Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type gteeterService struct {
	c    client.Client
	name string
}

func NewGteeterService(name string, c client.Client) GteeterService {
	return &gteeterService{
		c:    c,
		name: name,
	}
}

func (c *gteeterService) Hello(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Gteeter.Hello", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gteeter service

type GteeterHandler interface {
	Hello(context.Context, *Request, *Response) error
}

func RegisterGteeterHandler(s server.Server, hdlr GteeterHandler, opts ...server.HandlerOption) error {
	type gteeter interface {
		Hello(ctx context.Context, in *Request, out *Response) error
	}
	type Gteeter struct {
		gteeter
	}
	h := &gteeterHandler{hdlr}
	return s.Handle(s.NewHandler(&Gteeter{h}, opts...))
}

type gteeterHandler struct {
	GteeterHandler
}

func (h *gteeterHandler) Hello(ctx context.Context, in *Request, out *Response) error {
	return h.GteeterHandler.Hello(ctx, in, out)
}
